import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MobileMenu } from '../components/mobile-menu'
import { Header } from '../components/header'
import { useState } from 'react'
import styled, {css} from 'styled-components'
import Link from 'next/link'
import { Moon } from '../components/moon'
import { KeaPlayer } from '../components/kea-player'



export default function Home() {

const [viewMobileMenu, setViewMobileMenu] = useState(false)

function seeMobileMenu(){
  setViewMobileMenu(true)
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Lisa von Mond</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setViewMobileMenu={setViewMobileMenu}/>
        <MobileMenu viewMobileMenu={viewMobileMenu} setViewMobileMenu={setViewMobileMenu}/>

      <main className={styles.main}>
        <div className={styles.feature}>
        <div className={styles.featureinner}>
 
        <Moon/>

        </div>
        </div>

        <div className={styles.content}>
        <FixedIntro>
        <h2>LISA VON MOND</h2>
        <h3>ambient dub, dreamtunes, slow wave<br></br>sound production, composition and research</h3>
        </FixedIntro>

        </div>

      
      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
        legal notice
        </a>
        /
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
        privacy policy
        </a>
      </footer>
    </div>
  )
}



const FixedIntro = styled.div`

position: block;
display:flex;
flex-direction: column;
align-items: left;
justify-content:center;
padding-left: 0;



@media only screen and (min-width:800px)
{
position:fixed;
height: 100vh;
width: 60vw;
top: 0;
right: 0;
padding-left: 6rem;
z-index:80;

}


`



