import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MobileMenu } from '../components/mobile-menu'
import { Header } from '../components/header'
import { useState } from 'react'
import styled, {css} from 'styled-components'
import Link from 'next/link'
import { Moon } from '../components/moon'
import { Footer } from '../components/footer'
import stars from '../public/stars_bubble.gif'



export default function Home() {

const [viewMobileMenu, setViewMobileMenu] = useState(false)

function seeMobileMenu(){
  setViewMobileMenu(true)
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Lisa von Mond</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setViewMobileMenu={setViewMobileMenu}/>
        <MobileMenu viewMobileMenu={viewMobileMenu} setViewMobileMenu={setViewMobileMenu}/>

      <main className={styles.main}>
        <div className={styles.feature}>
        <div className={styles.featureinner}>
 
        <Moon/>

        </div>
        </div>

        <div className={styles.content}>
        <FixedIntro>
        <h1>LISA VON MOND</h1>
        <h3>ambient dub, dreamtunes, slow wave<br></br>sound production, composition and research</h3>
        </FixedIntro>
        <FixedImageOne>
          <Image src={stars} alt="stars" height="500" width="550"></Image>
        </FixedImageOne>
        </div>
      </main>

      <Footer/>
    </div>
  )
}


const FixedIntro = styled.div`

position: block;
display:flex;
flex-direction: column;
align-items: flex-start;
justify-content:center;
padding-left: 0;
text-align:left;
z-index:0;


@media only screen and (min-width:800px)
{
position:fixed;
height: 80vh;
width: 60vw;
top: 10vh;
right: 0;
padding-left: 6rem;


}`

const FixedImageOne = styled.div`

position: fixed;
top: 5%;
left:0;
display:flex;
align-items:center;
justify-content:center;
padding: 2rem;




@media only screen and (min-width:800px)
{


}`
