import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MobileMenu } from '../components/mobile-menu'
import { Header } from '../components/header'
import { useState } from 'react'
import testpic_one from '../public/test_circle.png'
import styled, {css} from 'styled-components'



export default function Home() {

const [viewMobileMenu, setViewMobileMenu] = useState(false)

function seeMobileMenu(){
  setViewMobileMenu(true)
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Lisa von Mond</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setViewMobileMenu={setViewMobileMenu}/>
        <MobileMenu viewMobileMenu={viewMobileMenu} setViewMobileMenu={setViewMobileMenu}/>

      <main className={styles.main}>
        <div className={styles.feature}>
        <Moon>
        <p className={styles.featuretext}>08/08/22</p>
        <p className={styles.featuretext}>increasing moon</p>
        <p className={styles.featuretext}>next full moon:</p>
        <p className={styles.featuretext}>12/08/22</p>
        </Moon>
        </div>

        <div className={styles.content}>
      
        <h2>LISA VON MOND</h2>
        <p>ambient dub, dreamtunes, slow wave<br></br>sound art and research</p>
        <h3>news * news * news</h3>
        <p>09/22: release of my EP <i>lovely planet</i> on HuL berlin<br></br>w/ remixes by thea, skydrips, Dana Anderson</p>
        <div className={styles.decoimage}>
       <Image src={testpic_one} width="500" height="500" alt="deco image"></Image>
       </div>


        </div>

      
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
        legal notice
        </a>
        /
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
        privacy policy
        </a>
      </footer>
    </div>
  )
}


const Moon = styled.div`
background-image: linear-gradient(to top, #ff9a9e 0%, #fecfef 99%, #fecfef 100%);
border-radius:1000px;
display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
aspect-ratio:1;
padding:2rem;
text-align:center;
gap:0.5rem;

@media only screen and (min-width:800px){
  position:fixed;
  left:15%;
  top:30%;
  padding:3rem;
}


`
