import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MobileMenu } from '../components/mobile-menu'
import { Header } from '../components/header'
import { useState } from 'react'
import testpic_one from '../public/test_circle.png'
import kea from '../public/kea.gif'
import youandme from '../public/you-and-me.gif'



export default function Home() {

const [viewMobileMenu, setViewMobileMenu] = useState(false)

function seeMobileMenu(){
  setViewMobileMenu(true)
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Lisa von Mond</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header setViewMobileMenu={setViewMobileMenu}/>
        <MobileMenu viewMobileMenu={viewMobileMenu} setViewMobileMenu={setViewMobileMenu}/>


        <div className={styles.content}>

        <h2>RELEASES</h2>
        <h3>kea // vak.leipzig</h3>
        <div className={styles.decoimage}>
        <Image src={kea} width="500" height="500"></Image>
        </div>
        <p>Kea is a smooth soundscape chillout, released may 2022 on Solisampler VAK03 of vak.leipzig collective. Revenues from the sampler go to SeaWatch e.B. and Blindspots e.V. - an organization that supports volunteer structures for Balkan and Ukraine refugees.</p>
        <p><a href="https://soundcloud.com/vak-leipzig/sets/vak03" target="blank" rel="noopener" className={styles.exlink}>Listen to Sampler on soundcloud</a></p>
        <p><a href="https://vak-leipzig.bandcamp.com/album/vak03" target="blank" rel="noopener" className={styles.exlink}>buy sampler on bandcamp</a></p>

        <div className={styles.rowspacer}> </div>

        <h3>You and me // friendly connections</h3>
        <div className={styles.decoimage}>
        <Image src={youandme} width="500" height="500"></Image>
        </div>
        <p>A warm and cosy downtempo track with influences of dub, house and ambient. Released may 2021 on the Bremen / Cologne label friendly connections</p>
        <p><a className={styles.exlink} href="https://soundcloud.com/friendlyconnections/lisa-von-mond-you-and-me" target="blank" rel="noopener">Listen to on soundcloud</a></p>
 
  
       </div>
      
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
        legal notice
        </a>
        /
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
        privacy policy
        </a>
      </footer>
    </div>
  )
}
