import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { MobileMenu } from '../components/mobile-menu'
import { Header } from '../components/header'
import { useState } from 'react'
import testpic_one from '../public/test_circle.png'
import kea from '../public/kea.gif'
import youandme from '../public/you-and-me.gif'
import styled, {css} from 'styled-components'
import { KeaPlayer } from '../components/kea-player'
import { YouAndMePlayer } from '../components/you-and-me-player'



export default function Home() {

const [viewMobileMenu, setViewMobileMenu] = useState(false)

function seeMobileMenu(){
  setViewMobileMenu(true)
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Lisa von Mond</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setViewMobileMenu={setViewMobileMenu}/>
        <MobileMenu viewMobileMenu={viewMobileMenu} setViewMobileMenu={setViewMobileMenu}/>

      <main className={styles.main}>

        <div className={styles.feature}>
        <div className={styles.featureinner}>
        <Cloud>
        <p className={styles.featuretext}><b>UPCOMING</b></p>
        <p className={styles.featuretext}>98/22 EP release<br></br>lovely planet<br></br>on HuL Berlin</p>
        </Cloud>
        </div>
        </div>

        <div className={styles.content}>

        <h2>RELEASES</h2>
        <h3>kea // vak.leipzig</h3>
        <div className={styles.decoimage}>
        <Image src={kea} width="500" height="500" alt="kea cover"></Image>
        </div>
        <KeaPlayer/>
        <p>A smooth soundscape chillout, released may 2022 on Solisampler VAK03 of vak.leipzig collective. Revenues from the sampler go to SeaWatch e.B. and Blindspots e.V. - an organization that supports volunteer structures for Balkan and Ukraine refugees.</p>
        <p><a href="https://soundcloud.com/vak-leipzig/sets/vak03" target="blank" rel="noopener" className={styles.exlink}>Listen to Sampler on soundcloud</a></p>
        <p><a href="https://vak-leipzig.bandcamp.com/album/vak03" target="blank" rel="noopener" className={styles.exlink}>buy sampler on bandcamp</a></p>
  
        <div className={styles.rowspacer}> </div>

        <h3>You and me // friendly connections</h3>
        <div className={styles.decoimage}>
        <Image src={youandme} width="500" height="500" alt="you and me cover"></Image>
        </div>
        <YouAndMePlayer/>
        <p>A warm and cosy downtempo track with influences of dub, house and ambient. Released may 2021 on the Bremen / Cologne label friendly connections</p>
        <p><a className={styles.exlink} href="https://soundcloud.com/friendlyconnections/lisa-von-mond-you-and-me" target="blank" rel="noopener">Listen to on soundcloud</a></p>
        <div className={styles.rowspacer}> </div>
  
       </div>
      
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
        legal notice
        </a>
        /
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
        privacy policy
        </a>
      </footer>
    </div>
  )
}


const Cloud = styled.div`
display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
padding:2rem;
text-align:center;
gap:0.5rem;

`